workflows:
  ios-workflow:
    name: iOS Fast Build

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa