workflows:
  ios-workflow:
    name: iOS Build Fixed

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Generate iOS config (الحل هنا 🔥)
        script: flutter build ios --debug --no-codesign

      - name: Build release
        script: flutter build ios --release --no-codesign