# السطر القادم ضروري جداً لتعريف أوامر Flutter داخل الملف
target_ios_revision = File.join(File.dirname(__FILE__), 'Flutter', 'generated_ios_development_target.rb')
load target_ios_revision if File.exist?(target_ios_revision)

platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_flutter_plugins!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end